# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: secrets

stages:
  - stage: CallThingworx
    jobs:
      - job: CallDevopsApi
        steps:
          - script:
              echo "Calling ThingWorx devopsApi..."

              JSON_BODY='{"body":"{\"action\":\"deploy\",\"target\":\"test\"}"}'

              curl -X POST "$(twx_url)" \
              -H "Content-Type:application/json" \
              -H "Accept:application/json" \
              -H "appKey:$appkey" \
              -H "x-thingworx-session:true" \
              -d "$JSON_BODY"
