# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main
pr:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: secrets

stages:
  - stage: CallCodebeamer
    jobs:
      - job: CallDevopsApi
        steps:
          - script: |
              echo "Calling Codebeamer devopsApi..."
              echo "URL = $CODEBEAMER_URL"

              curl -X GET "$CODEBEAMER_URL" \
              -H "Content-Type:application/json" \
              -H "Accept:application/json" \
              -H "Authorization:Basic RWxpYXp6YXJpdG86QHhibXdCZk5yOVplVQ==" \
            env:
              THINGWORX_URL: $(CODEBEAMER_URL)

